app:
  name: sb-config
  message: Hello User, you are in ${app.name}
  list: One, Two, Three
  map: "{name:'javawiz', appName:'sb-config'}"

sample:
  name: javawiz-test
  version: 1.0

management.endpoints.web.exposure.include: "*"
